name: SonarCloud Scan
description: Perform static code analysis using SonarCloud

inputs:
  sonar-project:
    required: true
  sonar-org:
    required: true

runs:
  using: composite
  steps:

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
      shell: bash

    - name: Begin Sonar Scan
      run: |
        dotnet sonarscanner begin \
        /k:"${{ inputs.sonar-project }}" \
        /o:"${{ inputs.sonar-org }}" \
        /d:sonar.token="${{ env.SONAR_TOKEN }}" \
        /d:sonar.host.url="https://sonarcloud.io"
      shell: bash

    - name: Build Project
      run: dotnet build src/hello-world-api
      shell: bash

    - name: End Sonar Scan
      run: |
        dotnet sonarscanner end \
        /d:sonar.token="${{ env.SONAR_TOKEN }}"
      shell: bash

    - name: SonarCloud Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      with:
        scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}