name: Dotnet CI Pipeline

on:
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build/build-dotnet.yml

  dependency-scan:
    needs: build
    uses: ./.github/workflows/security/dependency-vulnerability-scan.yml

  static-scan:
    needs: build
    uses: ./.github/workflows/security/static-code-scan.yml

  test:
    needs: build
    uses: ./.github/workflows/testing/unit-tests.yml

  docker-build:
    needs: [test, static-scan]
    uses: ./.github/workflows/container/docker-build.yml

  container-scan:
    needs: docker-build
    uses: ./.github/workflows/container/container-scan.yml

  deploy:
    needs: container-scan
    uses: ./.github/workflows/deploy/deploy-aca.yml