name: Deploy to Azure Container Apps

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Simulate Deployment
      run: |
        echo "Deploying container to Azure Container Apps..."
        echo "POC deployment successful"