name: Docker Build, Scan and Push

on:
  workflow_call:

jobs:
# Performing Build, scan and push on same stage as we have to use the same runner.
  docker-build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Package application into a container
      - name: Build Docker Image
        run: docker build -t poc-dotnet-app .

      # Trivy scans container image for vulnerabilities
      - name: Container Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: poc-dotnet-app

      # ensure image is not too large
      - name: Image Size Validator
        run: |
          SIZE=$(docker image inspect poc-dotnet-app --format='{{.Size}}')
          echo "Image Size: $SIZE bytes"

     # push image to registry
      - name: POC Image Push
        run: echo "Image would be pushed to registry here"
      # Azure Login and push to acr can be added here.