name: Platform CI Pipeline POC

on:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:

  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


  credential-scan:
    name: Credentials scanning
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/credential-scan


  dependency-scan:
    name: Dependency Vulnerability Scanning
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dependency-scan


  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: [dependency-scan, credential-scan]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build


  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/security
        with:
          sonar-org: ${{ vars.SONAR_ORG }}
          sonar-project: ${{ vars.SONAR_PROJECT }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: static-code-analysis
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-test


# Performing build and scan on same runner
  docker-build-scan-push:
    name: Docker Build, Scan and Push
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/container