name: Platform CI Pipeline POC

on:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:

  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


  credential-scan:
    name: Credentials scanning
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Credential Scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2


  dependency-scan:
    name: Dependency Vulnerability Scanning
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .


  build-artifact:
    name: Build Artifact
    needs: [dependency-scan,credential-scan]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore src/hello-world-api

      - name: Build Application
        run: dotnet build src/hello-world-api --no-restore


  static-code-analysis:
    name: Static Code Analysis
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3


  unit-tests:
    name: Unit Testing
    needs: static-code-analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Run Unit Tests
        run: dotnet test src/hello-world-api

# Performing Build, scan and push on same stage as we have to use the same runner.
  docker-build-scan-push:
    name: Docker Build, Scan and Push
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t poc-dotnet-app .


      - name: Container Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: poc-dotnet-app


      - name: Image Size Validator
        run: |
          SIZE=$(docker image inspect poc-dotnet-app --format='{{.Size}}')
          echo "Image Size: $SIZE bytes"


      - name: POC Image Push
        run: echo "Image would be pushed to registry here"
      # Azure Login and push to acr can be added here.
      
