name: Platform CI Pipeline POC

on:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:

  checkout:
    name: Checkout
    uses: ./.github/workflows/checkout.yml


  credential-scan:
    name: Credentials scanning
    needs: checkout
    uses: ./.github/workflows/credentials-scan.yml


  dependency-scan:
    name: Dependency Vulnerability Scanning
    needs: checkout
    uses: ./.github/workflows/dependency-vulnerability-scan.yml


  build-artifact:
    name: Build Artifact
    needs: [dependency-scan,credential-scan]
    uses: ./.github/workflows/build-dotnet.yml


  static-code-analysis:
    name: Static Code Analysis
    needs: build-artifact
    uses: ./.github/workflows/static-code-scan.yml
    secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  unit-tests:
    name: Unit Testing
    needs: static-code-analysis
    uses: ./.github/workflows/unit-test.yml

# Performing Build, scan and push on same stage as we have to use the same runner.
  docker-build-scan-push:
    name: Docker Build, Scan and Push
    needs: unit-tests
    uses: ./ .github/workflows/docker-build-scan-push.yml
      
