name: SonarCloud Scan

on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud Scan
        run: |
          dotnet sonarscanner begin \
          /k:${{ vars.SONAR_PROJECT }} \
          /o:${{ vars.SONAR_ORG }} \
          /d:sonar.login=${{ secrets.SONAR_TOKEN }} \
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Application
        run: dotnet build src/hello-world-api

      - name: End SonarCloud Scan
        run: |
          dotnet sonarscanner end \
          /d:sonar.login=${{ secrets.SONAR_TOKEN }}