name: SonarCloud Scan

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar Scan
        run: |
          dotnet sonarscanner begin \
          /k:"varunarora2201" \
          /o:"varunarora2201" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Project
        run: dotnet build src/hello-world-api

      - name: End Sonar Scan
        run: |
          dotnet sonarscanner end \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"